//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SDL.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SDLCompiler.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class SDLLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		Bool=1, Char=2, Decimal=3, Double=4, Float=5, Int=6, Long=7, Model=8, 
		Service=9, Short=10, String=11, Void=12, Question=13, Comma=14, Colon=15, 
		Semicolon=16, LeftParen=17, RightParen=18, LeftBracket=19, RightBracket=20, 
		LeftBrace=21, RightBrace=22, LeftAngle=23, RightAngle=24, Identifier=25, 
		Whitespace=26, Newline=27, BlockComment=28, LineComment=29;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"Bool", "Char", "Decimal", "Double", "Float", "Int", "Long", "Model", 
		"Service", "Short", "String", "Void", "Question", "Comma", "Colon", "Semicolon", 
		"LeftParen", "RightParen", "LeftBracket", "RightBracket", "LeftBrace", 
		"RightBrace", "LeftAngle", "RightAngle", "Identifier", "Nondigit", "Digit", 
		"Whitespace", "Newline", "BlockComment", "LineComment"
	};


	public SDLLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SDLLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'bool'", "'char'", "'decimal'", "'double'", "'float'", "'int'", 
		"'long'", "'model'", "'service'", "'short'", "'string'", "'void'", "'?'", 
		"','", "':'", "';'", "'('", "')'", "'['", "']'", "'{'", "'}'", "'<'", 
		"'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "Bool", "Char", "Decimal", "Double", "Float", "Int", "Long", "Model", 
		"Service", "Short", "String", "Void", "Question", "Comma", "Colon", "Semicolon", 
		"LeftParen", "RightParen", "LeftBracket", "RightBracket", "LeftBrace", 
		"RightBrace", "LeftAngle", "RightAngle", "Identifier", "Whitespace", "Newline", 
		"BlockComment", "LineComment"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SDL.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SDLLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1F', '\xD6', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\a', '\x1A', '\xA5', '\n', '\x1A', '\f', '\x1A', '\xE', 
		'\x1A', '\xA8', '\v', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', 
		'\x3', '\x1C', '\x3', '\x1D', '\x6', '\x1D', '\xAF', '\n', '\x1D', '\r', 
		'\x1D', '\xE', '\x1D', '\xB0', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', 
		'\x3', '\x1E', '\x5', '\x1E', '\xB7', '\n', '\x1E', '\x3', '\x1E', '\x5', 
		'\x1E', '\xBA', '\n', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\a', '\x1F', '\xC2', '\n', 
		'\x1F', '\f', '\x1F', '\xE', '\x1F', '\xC5', '\v', '\x1F', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', 
		'\x3', ' ', '\x3', ' ', '\x3', ' ', '\a', ' ', '\xD0', '\n', ' ', '\f', 
		' ', '\xE', ' ', '\xD3', '\v', ' ', '\x3', ' ', '\x3', ' ', '\x3', '\xC3', 
		'\x2', '!', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', 
		'\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', 
		'\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', 
		'!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', 
		'\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', 
		'\x2', '\x37', '\x2', '\x39', '\x1C', ';', '\x1D', '=', '\x1E', '?', '\x1F', 
		'\x3', '\x2', '\x6', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', 
		'|', '\x3', '\x2', '\x32', ';', '\x4', '\x2', '\v', '\v', '\"', '\"', 
		'\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x2', '\xDA', '\x2', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\x41', '\x3', '\x2', '\x2', '\x2', '\x5', '\x46', 
		'\x3', '\x2', '\x2', '\x2', '\a', 'K', '\x3', '\x2', '\x2', '\x2', '\t', 
		'S', '\x3', '\x2', '\x2', '\x2', '\v', 'Z', '\x3', '\x2', '\x2', '\x2', 
		'\r', '`', '\x3', '\x2', '\x2', '\x2', '\xF', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\x11', 'i', '\x3', '\x2', '\x2', '\x2', '\x13', 'o', '\x3', '\x2', 
		'\x2', '\x2', '\x15', 'w', '\x3', '\x2', '\x2', '\x2', '\x17', '}', '\x3', 
		'\x2', '\x2', '\x2', '\x19', '\x84', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'\x89', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', '\x8D', '\x3', '\x2', '\x2', '\x2', '!', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '#', '\x91', '\x3', '\x2', '\x2', '\x2', '%', '\x93', 
		'\x3', '\x2', '\x2', '\x2', '\'', '\x95', '\x3', '\x2', '\x2', '\x2', 
		')', '\x97', '\x3', '\x2', '\x2', '\x2', '+', '\x99', '\x3', '\x2', '\x2', 
		'\x2', '-', '\x9B', '\x3', '\x2', '\x2', '\x2', '/', '\x9D', '\x3', '\x2', 
		'\x2', '\x2', '\x31', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x33', '\xA1', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\xA9', '\x3', '\x2', '\x2', '\x2', 
		'\x37', '\xAB', '\x3', '\x2', '\x2', '\x2', '\x39', '\xAE', '\x3', '\x2', 
		'\x2', '\x2', ';', '\xB9', '\x3', '\x2', '\x2', '\x2', '=', '\xBD', '\x3', 
		'\x2', '\x2', '\x2', '?', '\xCB', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\x42', '\a', '\x64', '\x2', '\x2', '\x42', '\x43', '\a', 'q', '\x2', 
		'\x2', '\x43', '\x44', '\a', 'q', '\x2', '\x2', '\x44', '\x45', '\a', 
		'n', '\x2', '\x2', '\x45', '\x4', '\x3', '\x2', '\x2', '\x2', '\x46', 
		'G', '\a', '\x65', '\x2', '\x2', 'G', 'H', '\a', 'j', '\x2', '\x2', 'H', 
		'I', '\a', '\x63', '\x2', '\x2', 'I', 'J', '\a', 't', '\x2', '\x2', 'J', 
		'\x6', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\a', '\x66', '\x2', '\x2', 
		'L', 'M', '\a', 'g', '\x2', '\x2', 'M', 'N', '\a', '\x65', '\x2', '\x2', 
		'N', 'O', '\a', 'k', '\x2', '\x2', 'O', 'P', '\a', 'o', '\x2', '\x2', 
		'P', 'Q', '\a', '\x63', '\x2', '\x2', 'Q', 'R', '\a', 'n', '\x2', '\x2', 
		'R', '\b', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\a', '\x66', '\x2', 
		'\x2', 'T', 'U', '\a', 'q', '\x2', '\x2', 'U', 'V', '\a', 'w', '\x2', 
		'\x2', 'V', 'W', '\a', '\x64', '\x2', '\x2', 'W', 'X', '\a', 'n', '\x2', 
		'\x2', 'X', 'Y', '\a', 'g', '\x2', '\x2', 'Y', '\n', '\x3', '\x2', '\x2', 
		'\x2', 'Z', '[', '\a', 'h', '\x2', '\x2', '[', '\\', '\a', 'n', '\x2', 
		'\x2', '\\', ']', '\a', 'q', '\x2', '\x2', ']', '^', '\a', '\x63', '\x2', 
		'\x2', '^', '_', '\a', 'v', '\x2', '\x2', '_', '\f', '\x3', '\x2', '\x2', 
		'\x2', '`', '\x61', '\a', 'k', '\x2', '\x2', '\x61', '\x62', '\a', 'p', 
		'\x2', '\x2', '\x62', '\x63', '\a', 'v', '\x2', '\x2', '\x63', '\xE', 
		'\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', 'n', '\x2', '\x2', '\x65', 
		'\x66', '\a', 'q', '\x2', '\x2', '\x66', 'g', '\a', 'p', '\x2', '\x2', 
		'g', 'h', '\a', 'i', '\x2', '\x2', 'h', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'i', 'j', '\a', 'o', '\x2', '\x2', 'j', 'k', '\a', 'q', '\x2', '\x2', 
		'k', 'l', '\a', '\x66', '\x2', '\x2', 'l', 'm', '\a', 'g', '\x2', '\x2', 
		'm', 'n', '\a', 'n', '\x2', '\x2', 'n', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'o', 'p', '\a', 'u', '\x2', '\x2', 'p', 'q', '\a', 'g', '\x2', '\x2', 
		'q', 'r', '\a', 't', '\x2', '\x2', 'r', 's', '\a', 'x', '\x2', '\x2', 
		's', 't', '\a', 'k', '\x2', '\x2', 't', 'u', '\a', '\x65', '\x2', '\x2', 
		'u', 'v', '\a', 'g', '\x2', '\x2', 'v', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'w', 'x', '\a', 'u', '\x2', '\x2', 'x', 'y', '\a', 'j', '\x2', '\x2', 
		'y', 'z', '\a', 'q', '\x2', '\x2', 'z', '{', '\a', 't', '\x2', '\x2', 
		'{', '|', '\a', 'v', '\x2', '\x2', '|', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'}', '~', '\a', 'u', '\x2', '\x2', '~', '\x7F', '\a', 'v', '\x2', '\x2', 
		'\x7F', '\x80', '\a', 't', '\x2', '\x2', '\x80', '\x81', '\a', 'k', '\x2', 
		'\x2', '\x81', '\x82', '\a', 'p', '\x2', '\x2', '\x82', '\x83', '\a', 
		'i', '\x2', '\x2', '\x83', '\x18', '\x3', '\x2', '\x2', '\x2', '\x84', 
		'\x85', '\a', 'x', '\x2', '\x2', '\x85', '\x86', '\a', 'q', '\x2', '\x2', 
		'\x86', '\x87', '\a', 'k', '\x2', '\x2', '\x87', '\x88', '\a', '\x66', 
		'\x2', '\x2', '\x88', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', 
		'\a', '\x41', '\x2', '\x2', '\x8A', '\x1C', '\x3', '\x2', '\x2', '\x2', 
		'\x8B', '\x8C', '\a', '.', '\x2', '\x2', '\x8C', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', '\x8D', '\x8E', '\a', '<', '\x2', '\x2', '\x8E', ' ', '\x3', 
		'\x2', '\x2', '\x2', '\x8F', '\x90', '\a', '=', '\x2', '\x2', '\x90', 
		'\"', '\x3', '\x2', '\x2', '\x2', '\x91', '\x92', '\a', '*', '\x2', '\x2', 
		'\x92', '$', '\x3', '\x2', '\x2', '\x2', '\x93', '\x94', '\a', '+', '\x2', 
		'\x2', '\x94', '&', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\a', 
		']', '\x2', '\x2', '\x96', '(', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', 
		'\a', '_', '\x2', '\x2', '\x98', '*', '\x3', '\x2', '\x2', '\x2', '\x99', 
		'\x9A', '\a', '}', '\x2', '\x2', '\x9A', ',', '\x3', '\x2', '\x2', '\x2', 
		'\x9B', '\x9C', '\a', '\x7F', '\x2', '\x2', '\x9C', '.', '\x3', '\x2', 
		'\x2', '\x2', '\x9D', '\x9E', '\a', '>', '\x2', '\x2', '\x9E', '\x30', 
		'\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\a', '@', '\x2', '\x2', '\xA0', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA6', '\x5', '\x35', '\x1B', 
		'\x2', '\xA2', '\xA5', '\x5', '\x35', '\x1B', '\x2', '\xA3', '\xA5', '\x5', 
		'\x37', '\x1C', '\x2', '\xA4', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA4', 
		'\xA3', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA8', '\x3', '\x2', '\x2', 
		'\x2', '\xA6', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', '\x3', 
		'\x2', '\x2', '\x2', '\xA7', '\x34', '\x3', '\x2', '\x2', '\x2', '\xA8', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAA', '\t', '\x2', '\x2', 
		'\x2', '\xAA', '\x36', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\t', 
		'\x3', '\x2', '\x2', '\xAC', '\x38', '\x3', '\x2', '\x2', '\x2', '\xAD', 
		'\xAF', '\t', '\x4', '\x2', '\x2', '\xAE', '\xAD', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xAE', '\x3', 
		'\x2', '\x2', '\x2', '\xB0', '\xB1', '\x3', '\x2', '\x2', '\x2', '\xB1', 
		'\xB2', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\b', '\x1D', '\x2', 
		'\x2', '\xB3', ':', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB6', '\a', 
		'\xF', '\x2', '\x2', '\xB5', '\xB7', '\a', '\f', '\x2', '\x2', '\xB6', 
		'\xB5', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', '\x3', '\x2', '\x2', 
		'\x2', '\xB7', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xBA', '\a', 
		'\f', '\x2', '\x2', '\xB9', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'\xB8', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBB', '\x3', '\x2', '\x2', 
		'\x2', '\xBB', '\xBC', '\b', '\x1E', '\x2', '\x2', '\xBC', '<', '\x3', 
		'\x2', '\x2', '\x2', '\xBD', '\xBE', '\a', '\x31', '\x2', '\x2', '\xBE', 
		'\xBF', '\a', ',', '\x2', '\x2', '\xBF', '\xC3', '\x3', '\x2', '\x2', 
		'\x2', '\xC0', '\xC2', '\v', '\x2', '\x2', '\x2', '\xC1', '\xC0', '\x3', 
		'\x2', '\x2', '\x2', '\xC2', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC3', 
		'\xC4', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC1', '\x3', '\x2', '\x2', 
		'\x2', '\xC4', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', 
		'\x2', '\x2', '\x2', '\xC6', '\xC7', '\a', ',', '\x2', '\x2', '\xC7', 
		'\xC8', '\a', '\x31', '\x2', '\x2', '\xC8', '\xC9', '\x3', '\x2', '\x2', 
		'\x2', '\xC9', '\xCA', '\b', '\x1F', '\x2', '\x2', '\xCA', '>', '\x3', 
		'\x2', '\x2', '\x2', '\xCB', '\xCC', '\a', '\x31', '\x2', '\x2', '\xCC', 
		'\xCD', '\a', '\x31', '\x2', '\x2', '\xCD', '\xD1', '\x3', '\x2', '\x2', 
		'\x2', '\xCE', '\xD0', '\n', '\x5', '\x2', '\x2', '\xCF', '\xCE', '\x3', 
		'\x2', '\x2', '\x2', '\xD0', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD1', 
		'\xCF', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xD2', '\x3', '\x2', '\x2', 
		'\x2', '\xD2', '\xD4', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD1', '\x3', 
		'\x2', '\x2', '\x2', '\xD4', '\xD5', '\b', ' ', '\x2', '\x2', '\xD5', 
		'@', '\x3', '\x2', '\x2', '\x2', '\n', '\x2', '\xA4', '\xA6', '\xB0', 
		'\xB6', '\xB9', '\xC3', '\xD1', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace SDLCompiler.Parser
