//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SDL.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SDLCompiler.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SDLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ISDLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SDLParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] SDLParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SDLParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] SDLParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SDLParser.modelDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelDeclaration([NotNull] SDLParser.ModelDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SDLParser.modelMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelMember([NotNull] SDLParser.ModelMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SDLParser.serviceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitServiceDeclaration([NotNull] SDLParser.ServiceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SDLParser.serviceMethod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitServiceMethod([NotNull] SDLParser.ServiceMethodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SDLParser.methodParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodParameterList([NotNull] SDLParser.MethodParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SDLParser.methodParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodParameter([NotNull] SDLParser.MethodParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SDLParser.typeOrVoid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeOrVoid([NotNull] SDLParser.TypeOrVoidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SDLParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] SDLParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SDLParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayType([NotNull] SDLParser.ArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SDLParser.basicType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasicType([NotNull] SDLParser.BasicTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SDLParser.modelType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelType([NotNull] SDLParser.ModelTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SDLParser.internalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInternalType([NotNull] SDLParser.InternalTypeContext context);
}
} // namespace SDLCompiler.Parser
